spring:
  profiles:
    active: dev

server:
  port: ${SERVER_PORT:8080}

room:
  timeSlot:
    pending:
      expiration:
        minutes: 40
    rollingWindow:
      days: ${ROLLING_WINDOW_DAYS:30}
